# Generated by Django 2.1.7 on 2019-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190228_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(max_length=50, upload_to='song_file/%Y/%m', verbose_name='歌曲文件'),
        ),
    ]
