# Generated by Django 2.1.7 on 2019-02-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190228_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.CharField(max_length=50, verbose_name='歌曲文件'),
        ),
    ]
