# Generated by Django 2.1.7 on 2019-02-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20190228_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_img',
            field=models.CharField(max_length=20, verbose_name='歌曲图片'),
        ),
    ]
